require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SchedaFumettosController do

  # This should return the minimal set of attributes required to create a valid
  # SchedaFumetto. As you add validations to SchedaFumetto, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SchedaFumettosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all scheda_fumettos as @scheda_fumettos" do
      scheda_fumetto = SchedaFumetto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scheda_fumettos).should eq([scheda_fumetto])
    end
  end

  describe "GET show" do
    it "assigns the requested scheda_fumetto as @scheda_fumetto" do
      scheda_fumetto = SchedaFumetto.create! valid_attributes
      get :show, {:id => scheda_fumetto.to_param}, valid_session
      assigns(:scheda_fumetto).should eq(scheda_fumetto)
    end
  end

  describe "GET new" do
    it "assigns a new scheda_fumetto as @scheda_fumetto" do
      get :new, {}, valid_session
      assigns(:scheda_fumetto).should be_a_new(SchedaFumetto)
    end
  end

  describe "GET edit" do
    it "assigns the requested scheda_fumetto as @scheda_fumetto" do
      scheda_fumetto = SchedaFumetto.create! valid_attributes
      get :edit, {:id => scheda_fumetto.to_param}, valid_session
      assigns(:scheda_fumetto).should eq(scheda_fumetto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SchedaFumetto" do
        expect {
          post :create, {:scheda_fumetto => valid_attributes}, valid_session
        }.to change(SchedaFumetto, :count).by(1)
      end

      it "assigns a newly created scheda_fumetto as @scheda_fumetto" do
        post :create, {:scheda_fumetto => valid_attributes}, valid_session
        assigns(:scheda_fumetto).should be_a(SchedaFumetto)
        assigns(:scheda_fumetto).should be_persisted
      end

      it "redirects to the created scheda_fumetto" do
        post :create, {:scheda_fumetto => valid_attributes}, valid_session
        response.should redirect_to(SchedaFumetto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scheda_fumetto as @scheda_fumetto" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchedaFumetto.any_instance.stub(:save).and_return(false)
        post :create, {:scheda_fumetto => {  }}, valid_session
        assigns(:scheda_fumetto).should be_a_new(SchedaFumetto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchedaFumetto.any_instance.stub(:save).and_return(false)
        post :create, {:scheda_fumetto => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scheda_fumetto" do
        scheda_fumetto = SchedaFumetto.create! valid_attributes
        # Assuming there are no other scheda_fumettos in the database, this
        # specifies that the SchedaFumetto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SchedaFumetto.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => scheda_fumetto.to_param, :scheda_fumetto => { "these" => "params" }}, valid_session
      end

      it "assigns the requested scheda_fumetto as @scheda_fumetto" do
        scheda_fumetto = SchedaFumetto.create! valid_attributes
        put :update, {:id => scheda_fumetto.to_param, :scheda_fumetto => valid_attributes}, valid_session
        assigns(:scheda_fumetto).should eq(scheda_fumetto)
      end

      it "redirects to the scheda_fumetto" do
        scheda_fumetto = SchedaFumetto.create! valid_attributes
        put :update, {:id => scheda_fumetto.to_param, :scheda_fumetto => valid_attributes}, valid_session
        response.should redirect_to(scheda_fumetto)
      end
    end

    describe "with invalid params" do
      it "assigns the scheda_fumetto as @scheda_fumetto" do
        scheda_fumetto = SchedaFumetto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchedaFumetto.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheda_fumetto.to_param, :scheda_fumetto => {  }}, valid_session
        assigns(:scheda_fumetto).should eq(scheda_fumetto)
      end

      it "re-renders the 'edit' template" do
        scheda_fumetto = SchedaFumetto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchedaFumetto.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheda_fumetto.to_param, :scheda_fumetto => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scheda_fumetto" do
      scheda_fumetto = SchedaFumetto.create! valid_attributes
      expect {
        delete :destroy, {:id => scheda_fumetto.to_param}, valid_session
      }.to change(SchedaFumetto, :count).by(-1)
    end

    it "redirects to the scheda_fumettos list" do
      scheda_fumetto = SchedaFumetto.create! valid_attributes
      delete :destroy, {:id => scheda_fumetto.to_param}, valid_session
      response.should redirect_to(scheda_fumettos_url)
    end
  end

end
